# Trigger
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


# Function
jobs:
  # Build Job
  build: 
    name: Build
    runs-on: ubuntu-latest
    # Step
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: Install NPM Dependencies
        run: npm i axios
      - name: Build Project
        run: npm run build
      - name: Upload artifact in order to deploy
        uses: actions/upload-artifact@v2
        with: 
          name: deployment-files
          path: ./build
  # Deploy Job
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps: 
      - name: Download artifact
        uses: actions/download-artifact@v2
        with: 
          name: deployment-files
          path: ./build
      - name: Deploy to pages
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: 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
          publish_dir: ./build
